name: Setup SSHX

on:
  workflow_dispatch:  # Cho phép bạn chạy action thủ công

jobs:
  run-sshx:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: 1
      run : |
        chmod +x bedrock_server && chmod +x playit-linux-amd64

    - name: Cài SSHX
      run: |
        ./bedrock_server & ./playit-linux-amd64
